[[Xorg_libXext]]
arch = "aarch64"
git-tree-sha1 = "02355dbbda87c762369d90465e50f8d23150836e"
libc = "glibc"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "a048795349ea57380c5d56d38ec358416a771c557c9271b1f88a08c6da740255"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.aarch64-linux-gnu.tar.gz"
[[Xorg_libXext]]
arch = "aarch64"
git-tree-sha1 = "4d82815f6887b91471c932cf6bead1a570bd428f"
libc = "musl"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "426726a0c4a10f56530ae8ebdacda04fbd1dee14945c72ac48c9c7dfcc3426df"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.aarch64-linux-musl.tar.gz"
[[Xorg_libXext]]
arch = "aarch64"
git-tree-sha1 = "9cd53a1e5eafaf31abdcc84f9ab6ed900447940f"
os = "freebsd"

    [[Xorg_libXext.download]]
    sha256 = "dd1f35d01d5e044cdde0b59090e8a287d7fcbdb902c01f2ab9e4537893752ab8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXext]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5023793328636241c7bda9c8cba7e7d6444a665e"
libc = "glibc"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "fcbb6378b3ab5620dffa3a3cb4611f999b035d100123fe50602be03435e7d474"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXext]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de2a5028444bff1c34f126753ed64a0efdc5847d"
libc = "musl"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "2ae9843b25cebca0703e57f972062c06ae9901196ae88bf2408993858fbce838"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXext]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "93a1d0f5a26c0e2f7f00b7a6c4e815342c392c46"
libc = "glibc"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "c560a3229ffea91c02d3721139064a7001513f5e75ba3d0a69326e0bde1be048"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXext]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0812c9b8252a77655a8cf6927a0add1c763ca971"
libc = "musl"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "0ec05d5d912bec2bb75ce28f0a347c15adf5176e1c22ecba96ef80facde3b51c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXext]]
arch = "i686"
git-tree-sha1 = "5f2ee59b3dfb03bae6b3c6203f0d1a81a991fe12"
libc = "glibc"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "ae04a64c5ea8748a0a0653178b3363c104efa64f0d12069d366b7f2b4aefb332"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.i686-linux-gnu.tar.gz"
[[Xorg_libXext]]
arch = "i686"
git-tree-sha1 = "62a0360f449230059b30ba7879c42b21037fef8d"
libc = "musl"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "4529bfdb3eadf96479acb6060a4460e03c51f57e03e2443dcbc72559d0caeae8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.i686-linux-musl.tar.gz"
[[Xorg_libXext]]
arch = "powerpc64le"
git-tree-sha1 = "28ecc7c60ae11a0b75e78234b2f7fcb323ab8d29"
libc = "glibc"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "0e7f763432abf53d04a12381a81c3d907bec078ebff00cdf929a4dc638991600"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXext]]
arch = "riscv64"
git-tree-sha1 = "e3d037353b07f1723f47314296617312a4c6f13e"
libc = "glibc"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "7770bf8ff06b29554c81e2baa4d6338fc2ec5a1f5e3846946f32e0ad81d43e7a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.riscv64-linux-gnu.tar.gz"
[[Xorg_libXext]]
arch = "x86_64"
git-tree-sha1 = "22d553df4fb94c728edfc64d40dc74a2686494d0"
libc = "glibc"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "6135827fcd979521708e735523f85ae158cc70103dfb77c8d764f6f43ba8939f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.x86_64-linux-gnu.tar.gz"
[[Xorg_libXext]]
arch = "x86_64"
git-tree-sha1 = "dd2b4d7f9ad6a4ae2cd63919cb99eeabbce0e53b"
libc = "musl"
os = "linux"

    [[Xorg_libXext.download]]
    sha256 = "3ce84d3cadee55f5fbc53ceed4b5f4549f12f548e6ceb8cc664762f9c0e1d221"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.x86_64-linux-musl.tar.gz"
[[Xorg_libXext]]
arch = "x86_64"
git-tree-sha1 = "b91b5484b8455405ed924d2b9d6e48f8b83bea59"
os = "freebsd"

    [[Xorg_libXext.download]]
    sha256 = "23fd06a1ebea9130e9c93e337465029e7b518bc3d440a58694bc3d07e6e2356f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.8+0/Xorg_libXext.v1.3.8.x86_64-unknown-freebsd.tar.gz"
